### ISSUE TITLE
Show all failures (don't stop after first failure)

### ISSUE THREAD

**Issue by jimkring** [marcpage/pylavi#66]
**Is your feature request related to a problem? Please describe.**
I am running pylavi for the first time on a codebase and I'd like to know all the failures. Right now, it appears to exit immediately after the first failure.  I can also imagine that when a user pushes code, they will have to fix *all the failures* and only noticing them one at a time (fixing, committing, pushing, and waiting for CI to inform about the next failure) will be quite time consuming.

**Describe the solution you'd like**
It would be nice to have an option to test all the VIs in the project (to completion even if a failure occurs) and output a list of all the failures at the end.

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks for the great tool!

**Comment by marcpage** [comment]
@jimkring This issue is now fixed live in pylavi 0.3.2. Please upgrade your dependency and verify this fixes your issue.

**Comment by jimkring** [comment]
@marcpage it seems to work well now -- I see two failures in my results after adding a couple different failure conditions.  Thanks a bunch!
